import { X, Phone, Hash, AlertCircle, Share2, Download } from 'lucide-react'
import Card from './Card'
import StatusPill from './StatusPill'
import Button from './Button'
import QRCode from 'qrcode'
import { useState } from 'react'

export default function VetPassModal({ pet, owner, onClose }) {
  const [sharingVetPass, setSharingVetPass] = useState(false)
  
  // Format vaccination status
  const getVaccinationStatus = () => {
    // Check if medicalInfo contains vaccination keywords
    const info = pet.medicalInfo?.toLowerCase() || ''
    if (info.includes('vaccinated') || info.includes('up to date') || info.includes('aktualne')) {
      return { status: 'Current', color: 'teal' }
    } else if (info.includes('expired') || info.includes('overdue') || info.includes('przeterminowane')) {
      return { status: 'Expired', color: 'coral' }
    } else {
      return { status: 'Unknown', color: 'amber' }
    }
  }
  
  const vaccinationStatus = getVaccinationStatus()
  
  // Generate shareable text summary
  const generateVetPassText = () => {
    return `
🐾 PAWAY VET PASS 🐾

Pet: ${pet.name}
Breed: ${pet.breed || 'N/A'}
Age: ${pet.age ? `${pet.age} years` : 'N/A'}
Weight: ${pet.weight ? `${pet.weight} kg` : 'N/A'}
Gender: ${pet.gender === 'male' ? 'Male ♂️' : 'Female ♀️'}

${pet.chipNumber ? `🔢 Chip: ${pet.chipNumber}` : ''}

💉 Vaccinations: ${vaccinationStatus.status}

${pet.medicalInfo ? `⚠️ Medical Notes:\n${pet.medicalInfo}` : ''}

${pet.behaviorTags?.length > 0 ? `\n🎯 Behavior: ${pet.behaviorTags.join(', ')}` : ''}

📞 Owner Contact: ${owner?.phone || owner?.email || 'N/A'}

---
Generated by Paway App
    `.trim()
  }
  
  const handleShare = async () => {
    setSharingVetPass(true)
    try {
      const text = generateVetPassText()
      
      // Try Web Share API first (works on mobile)
      if (navigator.share) {
        await navigator.share({
          title: `${pet.name} - Vet Pass`,
          text: text,
        })
      } else {
        // Fallback: Copy to clipboard
        await navigator.clipboard.writeText(text)
        alert('Vet Pass skopiowany do schowka!')
      }
    } catch (error) {
      console.error('Error sharing Vet Pass:', error)
      // Fallback: Copy to clipboard
      try {
        await navigator.clipboard.writeText(generateVetPassText())
        alert('Vet Pass skopiowany do schowka!')
      } catch (clipboardError) {
        console.error('Clipboard error:', clipboardError)
        alert('Nie udało się udostępnić')
      }
    } finally {
      setSharingVetPass(false)
    }
  }
  
  const handleDownloadQR = async () => {
    try {
      const qrData = await QRCode.toDataURL(generateVetPassText(), {
        width: 400,
        margin: 2,
        color: {
          dark: '#0D1712',
          light: '#FFFFFF'
        }
      })
      
      // Create download link
      const link = document.createElement('a')
      link.href = qrData
      link.download = `${pet.name}_VetPass_QR.png`
      link.click()
    } catch (error) {
      console.error('Error generating QR code:', error)
      alert('Failed to generate QR code')
    }
  }
  
  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50 overflow-y-auto">
      <div className="bg-card rounded-2xl p-6 max-w-lg w-full my-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="font-poppins font-bold text-2xl text-text-dark">Vet Pass 📄</h2>
            <p className="font-inter text-sm text-text-gray">Podsumowanie medyczne</p>
          </div>
          <button
            onClick={onClose}
            className="text-text-gray hover:text-text-dark transition-colors"
          >
            <X size={24} />
          </button>
        </div>
        
        {/* Pet Header */}
        <div className="flex items-center gap-4 mb-6 p-4 bg-lime-gradient rounded-xl">
          {pet.photos?.[0] ? (
            <img
              src={pet.photos[0]}
              alt={pet.name}
              className="w-20 h-20 rounded-xl object-cover border-2 border-white"
            />
          ) : (
            <div className="w-20 h-20 bg-white rounded-xl flex items-center justify-center text-3xl">
              {pet.species === 'dog' ? '🐕' : pet.species === 'cat' ? '🐱' : '🐾'}
            </div>
          )}
          <div className="flex-1">
            <h3 className="font-poppins font-bold text-xl text-bg-dark">{pet.name}</h3>
            <p className="font-inter text-sm text-bg-dark/80">
              {pet.breed || (pet.species === 'dog' ? 'Dog' : pet.species === 'cat' ? 'Cat' : 'Pet')}
            </p>
            {pet.age && (
              <p className="font-inter text-xs text-bg-dark/70">{pet.age} years old</p>
            )}
          </div>
        </div>
        
        {/* Basic Info */}
        <div className="grid grid-cols-2 gap-3 mb-6">
          {pet.weight && (
            <Card>
              <p className="font-inter text-xs text-text-gray mb-1">Waga</p>
              <p className="font-inter text-lg font-semibold text-text-dark">{pet.weight} kg</p>
            </Card>
          )}
          {pet.gender && (
            <Card>
              <p className="font-inter text-xs text-text-gray mb-1">Płeć</p>
              <p className="font-inter text-lg font-semibold text-text-dark">
                {pet.gender === 'male' ? '♂️ Samiec' : '♀️ Samica'}
              </p>
            </Card>
          )}
        </div>
        
        {/* Chip Number */}
        {pet.chipNumber && (
          <Card className="mb-4 bg-card-2">
            <div className="flex items-center gap-2">
              <Hash size={16} className="text-text-gray" />
              <div className="flex-1">
                <p className="font-inter text-xs text-text-gray mb-1">Numer chipa</p>
                <p className="font-mono text-sm font-semibold text-text-dark break-all">
                  {pet.chipNumber}
                </p>
              </div>
            </div>
          </Card>
        )}
        
        {/* Vaccination Status */}
        <div className="mb-4">
          <p className="font-inter text-xs text-text-gray mb-2">Status szczepień</p>
          <StatusPill color={vaccinationStatus.color} className="text-sm">
            💉 {vaccinationStatus.status}
          </StatusPill>
        </div>
        
        {/* Medical Info */}
        {pet.medicalInfo && (
          <Card className="mb-4 bg-amber/5 border-amber/20">
            <div className="flex items-start gap-3">
              <AlertCircle size={20} className="text-amber flex-shrink-0 mt-0.5" />
              <div className="flex-1">
                <p className="font-inter text-xs text-text-gray mb-2">Notatki medyczne / Alergie</p>
                <p className="font-inter text-sm text-text-dark leading-relaxed whitespace-pre-wrap">
                  {pet.medicalInfo}
                </p>
              </div>
            </div>
          </Card>
        )}
        
        {/* Behavior Tags */}
        {pet.behaviorTags && pet.behaviorTags.length > 0 && (
          <div className="mb-4">
            <p className="font-inter text-xs text-text-gray mb-2">Zachowanie</p>
            <div className="flex flex-wrap gap-2">
              {pet.behaviorTags.map(tag => (
                <StatusPill key={tag} color="lime">
                  {tag.charAt(0).toUpperCase() + tag.slice(1)}
                </StatusPill>
              ))}
            </div>
          </div>
        )}
        
        {/* Owner Contact */}
        {(owner?.phone || owner?.email) && (
          <Card className="mb-6 bg-teal/5 border-teal/20">
            <div className="flex items-center gap-3">
              <Phone size={18} className="text-teal" />
              <div>
                <p className="font-inter text-xs text-text-gray mb-1">Kontakt do właściciela</p>
                <p className="font-inter text-sm font-semibold text-text-dark">
                  {owner.phone || owner.email}
                </p>
              </div>
            </div>
          </Card>
        )}
        
        {/* Action Buttons */}
        <div className="flex gap-3">
          <Button
            variant="secondary"
            onClick={handleDownloadQR}
            className="flex-1 flex items-center justify-center gap-2"
          >
            <Download size={18} />
            QR Code
          </Button>
          <Button
            variant="primary"
            onClick={handleShare}
            disabled={sharingVetPass}
            className="flex-1 flex items-center justify-center gap-2"
          >
            <Share2 size={18} />
            {sharingVetPass ? 'Udostępnianie...' : 'Udostępnij'}
          </Button>
        </div>
        
        <p className="font-inter text-xs text-text-faint mt-4 text-center">
          💚 Stworzono w aplikacji Paway
        </p>
      </div>
    </div>
  )
}
